version: "3.9"
services:
  asphyxia:
    image: nykma/asphyxia:latest
    build:
      context: .
      args:
        CORE_VERSION: 1.20
        PLUGIN_VERSION: 0.3
    ports:
    - 8083:8083
    - 5700:5700
    volumes:
    - './save:/app/save'
    - './config:/app/config'
    - './plugins:/app/plugins'
